In [1]:
import numpy as np

In [2]:
valoraciones = np.array([[8,7,8,5],[2,6,8,1],[8,8,9,5]])
valoraciones

array([[8, 7, 8, 5],
       [2, 6, 8, 1],
       [8, 8, 9, 5]])

Acceder a estos datos en la primera dimension son las filas y en la segunda son las columnas

In [3]:
valoraciones[0][1]

7

In [4]:
valoraciones[0,1]

7

In [12]:
valoraciones2 = np.array([[[8,7,8,5],[2,5,5,2]],[[2,6,8,4],[8,9,7,4]],[[8,8,9,3],[10,9,10,8]]])
valoraciones2

array([[[ 8,  7,  8,  5],
        [ 2,  5,  5,  2]],

       [[ 2,  6,  8,  4],
        [ 8,  9,  7,  4]],

       [[ 8,  8,  9,  3],
        [10,  9, 10,  8]]])

In [6]:
valoraciones2[0,1,2]

5

In [7]:
np.zeros((3,2,4))

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

Sumar un 1 a cada valor de la matriz

In [8]:
valoraciones2 + np.ones((3,2,4))

array([[[ 9.,  8.,  9.,  6.],
        [ 3.,  6.,  6.,  3.]],

       [[ 3.,  7.,  9.,  5.],
        [ 9., 10.,  8.,  5.]],

       [[ 9.,  9., 10.,  4.],
        [11., 10., 11.,  9.]]])

In [13]:
np.mean(valoraciones2)

6.458333333333333

In [15]:
np.mean(valoraciones2,axis = 2)

array([[7.  , 3.5 ],
       [5.  , 7.  ],
       [7.  , 9.25]])

In [16]:
np.reshape([1,2,3,4,5,6,7,8,9,10,11,12],(3,2,2))

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])

Genera números aleatorios en dimensiones que le ingresemos

In [17]:
np.random.rand(2,2)

array([[0.07104027, 0.87688176],
       [0.27847514, 0.57838681]])